### ISSUE TITLE
无法获取到鼠标信息

### ISSUE THREAD

**Issue by iszhangsc** [lihaoyun6/AirBattery#12]
如图，在设置中可以查看我的鼠标信息，但是在 `AirBattery` 中无法查看
<img width="523" alt="image" src="https://github.com/lihaoyun6/AirBattery/assets/41824454/1ee41c98-d9d6-4e6a-a565-a3d2c44ea1e6">

**Comment by iszhangsc** [comment]
鼠标又出现了，但是键盘又不见了.........

**Comment by lihaoyun6** [comment]
这涉及到蓝牙外设的省电策略.
AirBattery是通过读取BLE设备的"广播数据"来获取电池用量的. 但某些蓝牙外设一旦连接到主机之后(你的Mac), 它就会停止发送公开广播(这样会更省电)
所以当你的鼠标连接到你的Mac之后, AirBattery就无法获取到它的电池数据了. (Batteries/AirBuddy之类的App也有一样的问题)

而且不是所有的BLE设备都有一样的省电策略, 所以你可能会发现有的能读取, 有的读不到.
不过退一步来看, 你还可以从macOS菜单栏上自带的"蓝牙"菜单里看到电量, 或者使用macOS自带的电池小组件看到这些"已连接到主机"的蓝牙设备的电量

**Comment by lihaoyun6** [comment]
你这种情况就很典型了, 能读到是因为在"那一个瞬间", 鼠标还没有连接到Mac(可能休眠了)
所以AirBattery才有机会抢在Mac以先和外设进行通信, 从而获取到电池数据
而等你一晃鼠标, 或者一按键盘. 他们马上就又连回Mac上了, AirBattery就又抓瞎了

**Comment by iszhangsc** [comment]
那这个就只能图一乐了
