### ISSUE TITLE
一直会扫描别人的设备

### ISSUE THREAD

**Issue by JDIYYST** [lihaoyun6/AirBattery#14]
我来提个意见，显示的不错，但是也感觉到了一个缺点，比如我已经扫描到了自己的所有的设备，然后电脑还是一直弹出 iphone 蓝牙配对的消息（应该是扫描到了别人的手机），如果在工作场地（设备多的地方，或者有流动性的地方），体验就很差，相对于看电量的功能一直弹框对于个人是很难接受的，有解决的办法吗？（取消扫描后自己的设备也会消失）

**Comment by lihaoyun6** [comment]
我会在下个版本中加入"黑名单"功能, 允许用户主动屏蔽一些不属于自己的蓝牙设备, 敬请期待

**Comment by lihaoyun6** [comment]
v1.3.4版本已发布, 包含设备黑名单功能, 请更新尝试
