### ISSUE TITLE
无法识别鼠标

### ISSUE THREAD

**Issue by bugsmachine** [lihaoyun6/AirBattery#16]
鼠标是gpw2用usb转typec连在电脑上，所有的nearbility都打开了但是还是识别不出来鼠标 是罗技的没法识别嘛

**Comment by lihaoyun6** [comment]
这涉及到蓝牙外设的省电策略.
AirBattery是通过读取BLE设备的"广播数据"来获取电池用量的. 但某些蓝牙外设一旦连接到主机之后(你的Mac), 它就会停止发送公开广播(这样会更省电)  
所以当你的鼠标连接到你的Mac之后, AirBattery就无法获取到它的电池数据了. (Batteries/AirBuddy之类的App也有一样的问题)

**Comment by lihaoyun6** [comment]
不是所有的BLE设备都有一样的省电策略, 所以你可能会发现有的能读取, 有的读不到.
不过退一步来看, 你还可以从macOS菜单栏上自带的"蓝牙"菜单里看到电量, 或者使用macOS自带的电池小组件看到这些"已连接到主机"的蓝牙设备的电量
