### ISSUE TITLE
Action of opening the app when it is not shown in the dock

### ISSUE THREAD

**Issue by Alrazzouq** [lihaoyun6/AirBattery#17]
I really like this app. I have a problem. When I choose “Show AirBattery on: Status Bar” and open the application, it shows the application icon in the dock, and to hide it again I have to choose “Show AirBattery on” → Dock then Status Bar. This is not parctical. We need to control every thing from the menu bar icon without showing the dock icon.
What I suggest is on opening the application (or pressing on the widget) it opens the setting window (or you can make a dashboard instead of setting) which does not shows the application icon in the dock if I choose this option.

**Comment by lihaoyun6** [comment]
Which version of AirBattery are you using?

**Comment by Alrazzouq** [comment]
Version 1.3.1 (131)

**Comment by lihaoyun6** [comment]
You mean "Even if you have set AirBattery not to be showed on the Dock, the icon will still remain", right?
![image](https://github.com/lihaoyun6/AirBattery/assets/16348097/a9327a71-4470-4076-90f3-81f0d1cb0c9a)

**Comment by Alrazzouq** [comment]
It appears when I try to open the application from the Launchpad or duble click the widget. ""Even if you have set AirBattery not to be showed on the Dock,"

**Comment by lihaoyun6** [comment]
Ok, this will be fixed in the next version.  
When you set AirBattery to only appear on the menu bar, it will not show any Dock icon the next time you run it.

**Comment by Alrazzouq** [comment]
Thank you.

**Comment by lihaoyun6** [comment]
AirBattery v1.3.2 has been released. You can check for updates in the settings panel

**Comment by lihaoyun6** [comment]
If the Dock icon doesn't disappear after the update, right-click it and select "Remove from Dock", then it will never come back (unless you enable it again in settings)

**Comment by Alrazzouq** [comment]
I have recorded what happend when I dubble click on the widget. 
Also as you see in the video, there is  abug "Hidden divice". Please note, I dont have hidden devices. In my opinion, it is a good ideal to control hidden device from setting.

https://github.com/lihaoyun6/AirBattery/assets/171451552/abf8586a-5849-4bd5-bb0c-193912b49515

**Comment by Alrazzouq** [comment]
Thank you for updating the app. It works perfectly. I have more suggestions regarding “Single Device Widget”:
1- regarding the layout, could you decrease the size of the ring, increase the size of the icon of the device, and increase the size of the percentage of charging. And in the center of the circle, just keep the icon of the device, and put the percentage under the ring, and disable reviewing the name of the device.
2- Could you add an option to use more than one “Single Device Widget” each one for different device.

**Comment by Alrazzouq** [comment]
There is no signs of charging for iPhone. 
![Screenshot 2024-06-03 at 6 23 21 PM](https://github.com/lihaoyun6/AirBattery/assets/171451552/38a5e965-03ab-4cbc-9588-f86b82f1c1c6)

**Comment by lihaoyun6** [comment]
It usually takes 1~3 minutes to read the charging status of ios device via WiFi.
if you are using Bluetooth to search for iPhone, you also need to turn on "Guess charging status of iDevices or BLE devices over BT" in Settings. And it will take longer to get the result.

**Comment by lihaoyun6** [comment]
> Thank you for updating the app. It works perfectly. I have more suggestions regarding “Single Device Widget”: 1- regarding the layout, could you decrease the size of the ring, increase the size of the icon of the device, and increase the size of the percentage of charging. And in the center of the circle, just keep the icon of the device, and put the percentage under the ring, and disable reviewing the name of the device. (Or you can keep this layout and make another one) 2- Could you add an option to use more than one “Single Device Widget” each one for different device.

Hmm... I think I'll put it on my todo list.

**Comment by lihaoyun6** [comment]
The refresh interval of macOS widgets is not controlled by the App, so the device information in the widget lags behind the status bar menu.
<img width="360" alt="image" src="https://github.com/lihaoyun6/AirBattery/assets/16348097/7fcb8bab-eebc-4b9c-b282-91801ac2a563">

**Comment by Alrazzouq** [comment]
👍 It works after turning on the wifi in iPhone.
![Screenshot 2024-06-03 at 7 02 47 PM](https://github.com/lihaoyun6/AirBattery/assets/171451552/b2a69b55-efd7-47dd-b1bd-05b0739e530b)

**Comment by lihaoyun6** [comment]
> Thank you for updating the app. It works perfectly. I have more suggestions regarding “Single Device Widget”: 1- regarding the layout, could you decrease the size of the ring, increase the size of the icon of the device, and increase the size of the percentage of charging. And in the center of the circle, just keep the icon of the device, and put the percentage under the ring, and disable reviewing the name of the device. (Or you can keep this layout and make another one) 2- Could you add an option to use more than one “Single Device Widget” each one for different device.

AirBattery v1.3.4 has been released, including multiple bug fixes and new features.

Multiple single-device widgets can display different devices in macOS 14 now. Please check for updates😊

**Comment by Alrazzouq** [comment]
Thank you for updating the application. That is a great idea to show percentage in small widjet. Unfortnately, “Single Device Widget” does not work. It does not find any device. I think it is better to

**Comment by lihaoyun6** [comment]
If you want to use the new "configurable single-device widgets" in macOS 14, please delete the single-device widget created with the old version of AirBattery and re-add it, then right-click the widget to edit it and enter the name of the device you are looking for

**Comment by lihaoyun6** [comment]
You can also quickly copy the name of any device by clicking the "clipboard" icon at the end of the entry in the device list.

Please note: the widget may not refresh immediately, and do not click "Done" right after entering the device name, press Enter first to confirm your input, otherwise your input will be discarded (this is a macOS bug)

**Comment by Alrazzouq** [comment]
It works, thank you.
