### ISSUE TITLE
Popup window for Ignoring Device

### ISSUE THREAD

**Issue by Svec-Tomas** [lihaoyun6/AirBattery#18]
Hey! When I click ignore this device, nothing happens. I can only Cancel. I cancel and then this pop up window appears every few minutes again and again.
Using app on MacBook Pro M1 Pro, Sonoma 14.5
AirBattery 1.3.3 (133)

EDIT: By googling for SBF 77, it looks like it is a Silvercrest Scale, the bluetooth signal must come from neighbours apartment. The only thing for now, that helped was disabling the Beta feature - Try to get battery info from all BLE devices
![CleanShot 2024-06-03 at 12 01 45@2x](https://github.com/lihaoyun6/AirBattery/assets/138758322/7f6126ed-7c3d-454e-95f1-756e4498fc9a)

**Comment by lihaoyun6** [comment]
Yes, that's why it's a "Beta" feature...
I will add a "blacklist" feature in the next version to allow users to block certain Bluetooth devices.  
Thanks for your feedback

**Comment by lihaoyun6** [comment]
AirBattery v1.3.4 has been released, including multiple bug fixes and new features. Please check for updates😊

**Comment by Svec-Tomas** [comment]
I have updated and when I turn on the "Try to get battery info from all BLE devices" I still have the same issue. Does not seem to be solved for me.

**Comment by lihaoyun6** [comment]
Did you add it in the blacklist? Like this:  
<img width="500" alt="image" src="https://github.com/lihaoyun6/AirBattery/assets/16348097/8a0a7e4b-a18e-45e7-9a94-9af9b33f588a">

**Comment by Svec-Tomas** [comment]
Ah OK, I thought the new release fixed it and it is enough to tick the box here, to Ignore this Device:
![CleanShot 2024-06-10 at 12 52 39@2x](https://github.com/lihaoyun6/AirBattery/assets/138758322/8fffa823-084f-47f7-b114-d095abe768b0)
That does not work, but when I have added it to Blacklist, it helped and I don't get that request anymore.
