### ISSUE TITLE
appleWatch没有显示出来

### ISSUE THREAD

**Issue by MasterWangBo** [lihaoyun6/AirBattery#2]
AirPodspro和手机都显示出来了，但不知道为什么appleWatch没有显示出来，手机电脑都在一个WiFi下，补充一下电脑m1max，手表s6

**Comment by 17670454524** [comment]
一样，电脑m1 pro，手表s7

**Comment by lihaoyun6** [comment]
<img width="587" alt="image" src="https://github.com/lihaoyun6/AirBattery/assets/16348097/07901dae-4e61-46ad-81e9-93ea8ba4b275">  

### 调试数据的获取方法:  
1. 先将与 watch 配对使用的 iPhone 通过数据线连接到 Mac, 然后打开`终端`执行:
```bash
/Applications/AirBattery.app/Contents/Resources/libimobiledevice/bin/idevice_id
```
2. 之后将带有`(USB)`后缀的 ID 复制下来 (不含后缀), 再执行 (把0000替换成刚刚复制的ID):
```bash
/Applications/AirBattery.app/Contents/Resources/libimobiledevice/bin/comptest 0000
```
等待几秒钟看看程序能不能读取到 watch 的信息

**Comment by bboysoulcn** [comment]
> ```shell
> /Applications/AirBattery.app/Contents/Resources/libimobiledevice/bin/comptest
> ```

测试可以

**Comment by lihaoyun6** [comment]
> > ```shell
> > /Applications/AirBattery.app/Contents/Resources/libimobiledevice/bin/comptest
> > ```
> 
> 测试可以,但是退出应用之后重新打开应用还是会获取不到

可否将你通过终端获取到的手表数据信息发来给我看一下 (设备ID/序列号/设备名之类的隐私信息可以打码)

**Comment by bboysoulcn** [comment]
> > > ```shell
> > > /Applications/AirBattery.app/Contents/Resources/libimobiledevice/bin/comptest
> > > ```
> > 
> > 
> > 测试可以,但是退出应用之后重新打开应用还是会获取不到
> 
> 可否将你通过终端获取到的手表数据信息发来给我看一下 (设备ID/序列号/设备名之类的隐私信息可以打码)





```bash
❯ /Applications/AirBattery.app/Contents/Resources/libimobiledevice/bin/idevice_id

xxxxxxxxxxxx-xxxxxxxxxxxxxxx (USB)


❯ /Applications/AirBattery.app/Contents/Resources/libimobiledevice/bin/comptest xxxxxxxxxxxx-xxxxxxxxxxxxxxx
Waiting for phone...
Connected!
Retrieving list of watches...
Checking watch xxxxxxxxxxxx-xxxxxxxxxxxxxxx
ProductType: Watch7,1
SerialNumber: xxxxxxxxxxxxxx
DeviceName: xxxxxxxxxxxxxxxxx
BatteryCurrentCapacity: 72
BatteryIsCharging: false
```

**Comment by bboysoulcn** [comment]
> > > ```shell
> > > /Applications/AirBattery.app/Contents/Resources/libimobiledevice/bin/comptest
> > > ```
> > 
> > 
> > 测试可以,但是退出应用之后重新打开应用还是会获取不到
> 
> 可否将你通过终端获取到的手表数据信息发来给我看一下 (设备ID/序列号/设备名之类的隐私信息可以打码)

我感觉是因为我的手机是蓝牙发现的，手机和电脑不是一个wifi，退出应用再重新打开然后我就拿不到手表的数据了

**Comment by lihaoyun6** [comment]
> 我感觉是因为我的手机是蓝牙发现的，手机和电脑不是一个wifi，退出应用再重新打开然后我就拿不到手表的数据了

对, 是这样的. 手表的数据必须通过wifi获取, 蓝牙只能发现iPhone/iPad(蜂窝版), 不支持获取watch电量.
这不是bug, 苹果设计的数据通路就是这样的
