### ISSUE TITLE
Not detecting Logitech MX Master 3 for Mac

### ISSUE THREAD

**Issue by nomadjimbob** [lihaoyun6/AirBattery#20]
Bluetooth mouse, doesn't appear listed in AirBattery list but shown in the OS Bluetooth menu.

<img width="364" alt="Screenshot 2024-06-03 at 9 50 53 PM" src="https://github.com/lihaoyun6/AirBattery/assets/26953208/4f12512b-39e6-4719-9992-61b1ddf09e16">
<img width="310" alt="Screenshot 2024-06-03 at 9 51 09 PM" src="https://github.com/lihaoyun6/AirBattery/assets/26953208/248ffe66-4eeb-4866-a818-713fc9daec19">

Please let me know if there is something I should of done, or if there is anything I can do to help.

**Comment by lihaoyun6** [comment]
This involves the power saving strategy of Bluetooth peripherals.

AirBattery obtains battery usage by reading the "broadcast data" of BLE devices. But once some Bluetooth peripherals are connected to the host (your Mac), they will stop sending public broadcasts, which helps save power.

So when your mouse is connected to your Mac, AirBattery cannot obtain its battery data. (Batteries/AirBuddy also has the same problem)

**Comment by lihaoyun6** [comment]
And not all Bluetooth peripherals have the same power saving strategy, so some can be read and some cannot.

**Comment by badwulfy** [comment]
Hi, 
Thanks for the explication. I have a slightly different problem but maybe its linked ?
My MX Master seems to be detected in AirBattery but the battery percentage is incorrect (255%). In AirBuddy or in macOS Control Center, the real percentage is detected correctly.

**Comment by lihaoyun6** [comment]
> Hi, Thanks for the explication. I have a slightly different problem but maybe its linked ? My MX Master seems to be detected in AirBattery but the battery percentage is incorrect (255%). In AirBuddy or in macOS Control Center, the real percentage is detected correctly.

Please open the "System Information" App in the launchpad, and click "Bluetooth" in the list on the left, then find your device on the right and take a screenshot like this
<img width="324" alt="image" src="https://github.com/lihaoyun6/AirBattery/assets/48185104/131523cd-cbda-43ff-936e-75ca4e36baa9">

**Comment by nomadjimbob** [comment]
Incase you need a comparison for badwulfy, but as you said, I don't have a battery level listed.

<img width="340" alt="Screenshot 2024-06-04 at 5 20 48 PM" src="https://github.com/lihaoyun6/AirBattery/assets/26953208/71e91dde-13e0-418c-a8af-221e2574632b">

**Comment by badwulfy** [comment]
@lihaoyun6 Here is the system report:
<img width="270" alt="image" src="https://github.com/lihaoyun6/AirBattery/assets/3044771/729d034b-3c36-4163-a5b8-6e6c76ba8e3e">

**Comment by lihaoyun6** [comment]
> @lihaoyun6 Here is the system report: ...

Ok I got it, it will be fixed in the next update
