### ISSUE TITLE
No Icon for third-party headphones

### ISSUE THREAD

**Issue by rob-bc** [lihaoyun6/AirBattery#21]
<img width="356" alt="image" src="https://github.com/lihaoyun6/AirBattery/assets/48185104/36a42583-6f1e-4bc9-bdf0-f83e1bba24e9">

First widget is the native Battery widget, second is AirBattery. The 2nd icon should show headphones, but currently only a question mark icon is shown. The headphones model is Sennheiser Momentum 4.

Thanks for a great app!

**Comment by lihaoyun6** [comment]
Please open the "System Information" App in the launchpad, and click "Bluetooth" in the list on the left, then find your headphones on the right and take a screenshot like this
<img width="234" alt="image" src="https://github.com/lihaoyun6/AirBattery/assets/16348097/091c1768-2970-41e0-a6b5-966e4815ee2e">

**Comment by rob-bc** [comment]
<img width="324" alt="image" src="https://github.com/lihaoyun6/AirBattery/assets/48185104/131523cd-cbda-43ff-936e-75ca4e36baa9">

**Comment by lihaoyun6** [comment]
Ok, it will be fixed in the next version

**Comment by lihaoyun6** [comment]
AirBattery v1.3.4 has been released, including multiple bug fixes and new features. Please check for updates😊

**Comment by rob-bc** [comment]
New version works great, thanks!
