### ISSUE TITLE
Control Center Widget doesn't work on Ventura 13.6.1

### ISSUE THREAD

**Issue by Dybo007** [lihaoyun6/AirBattery#22]
Hi there, i don't really need it, but i've noticed that the lists are all empty! 

Ventura on M2 MBA.

**Comment by lihaoyun6** [comment]
AirBattery v1.3.4 has been released, including multiple bug fixes and new features. Please check for updates😊

**Comment by Dybo007** [comment]
I can confirm, it works now!! Thank you my friend!!
God bless you! Take care!!
