### ISSUE TITLE
AirBattery can't see magic keyboard.

### ISSUE THREAD

**Issue by Akis-P** [lihaoyun6/AirBattery#23]
Unfortunately, I can't see my Magic Keyboard in the list with bluetooth devices.

Magic Mouse, Pebble Bluetooth mouse and 3rd party bluetooth earbuds registering just fine.

Please advice 🙏🏻

**Comment by lihaoyun6** [comment]
Please open the "Terminal" App and run the following command:
```
ioreg -c AppleDeviceManagementHIDEventService > ~/Desktop/HID_Data.txt
```
Then send me the `HID_Data.txt` on your desktop

**Comment by Akis-P** [comment]
> Please open the "Terminal" App and run the following command:
> 
> ```
> ioreg -c AppleDeviceManagementHIDEventService > ~/Desktop/HID_Data.txt
> ```
> 
> Then send me the `HID_Data.txt` on your desktop


[HID_Data.txt](https://github.com/user-attachments/files/15545401/HID_Data.txt)

**Comment by lihaoyun6** [comment]
Oh, it looks like you're using an older model Magic Keyboard? Then you need to run:
```
ioreg -c AppleBluetoothHIDKeyboard > ~/Desktop/Old_HID_Data.txt
```

**Comment by lihaoyun6** [comment]
I will try to fix this in the next update

**Comment by lihaoyun6** [comment]
AirBattery v1.3.4 has been released, including multiple bug fixes and new features. Please check for updates😊

**Comment by Akis-P** [comment]
Thanks, looking forward to it.On 7 Jun 2024, at 10:43, lihaoyun6 ***@***.***> wrote:﻿
I will try to fix this in the next update
