### ISSUE TITLE
Widget dont working

### ISSUE THREAD

**Issue by soso4ek228** [lihaoyun6/AirBattery#25]
<img width="397" alt="Снимок экрана 2024-06-04 в 11 42 40" src="https://github.com/lihaoyun6/AirBattery/assets/73422209/7e22ed8c-e0eb-4f00-8d29-5175cb28dfdf">
MacOS 12.7.4 Macbook Pro 2015 15"

**Comment by lihaoyun6** [comment]
I'm aware of this bug and am working on fixing it.

**Comment by lihaoyun6** [comment]
AirBattery v1.3.4 has been released, including multiple bug fixes and new features. Please check for updates😊
