### ISSUE TITLE
Show AirPods together if battery percentage is almost same

### ISSUE THREAD

**Issue by dhruvkb** [lihaoyun6/AirBattery#26]
Apple's Battery widget shows the left and right AirPods together if their battery levels are similar. This makes it more convenient because it is not necessary to see the battery level of each AirPod separately.

<img width="386" alt="Screenshot 2024-06-04 at 2 51 48 PM" src="https://github.com/lihaoyun6/AirBattery/assets/16580576/fc7233ab-e6a7-4ff6-a960-467daf1ee8d2">

Please implement a similar feature in AirBattery. Also, thanks for building this incredible app, I have needed this for a long time.

**Comment by lihaoyun6** [comment]
<img width="326" alt="image" src="https://github.com/lihaoyun6/AirBattery/assets/16348097/594de60c-dca6-4a4d-8413-887b2cdc699b">  

Actually... AirBattery has this feature, but I set the "merge limit" to 3%

**Comment by lihaoyun6** [comment]
Maybe I'll raise it to 5%, or add a setting to allow users to customize this value🤔

**Comment by dhruvkb** [comment]
It's quite weird, my AirPods both start at a hundred but one depletes much faster than the other and the difference goes to even 20% by the time one dies. So a customisable value would be very helpful. Thank you.

**Comment by lihaoyun6** [comment]
Because the battery health of the two pods may be different (if you only wear one side often, it will be less durable)  
And the two pods do not communicate with the Mac at the same time, only one "Main" side is connected to the Mac, and then it forwards the data to the other side.  The "Main" pod consumes more power, so normally they take turns being the "Main".

**Comment by lihaoyun6** [comment]
<img width="981" alt="image" src="https://github.com/lihaoyun6/AirBattery/assets/16348097/0aaf82a6-1afd-43ea-a347-4a626b56829e">  
This feature will be implemented in the next update.

**Comment by dhruvkb** [comment]
Brilliant, thank you 🙏!

**Comment by Write** [comment]
> <img alt="image" width="981" src="https://private-user-images.githubusercontent.com/16348097/336872110-0aaf82a6-1afd-43ea-a347-4a626b56829e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NjU0NjUsIm5iZiI6MTcxNzc2NTE2NSwicGF0aCI6Ii8xNjM0ODA5Ny8zMzY4NzIxMTAtMGFhZjgyYTYtMWFmZC00M2VhLWEzNDctNGE2MjZiNTY4MjllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDEyNTkyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzZDNhODQwNWJiNzEyYzIzMzAxNTg3NGUxNDIyNmE5ZGMzN2IyNTJkYzExNjcxYTgwNGQ5Yjc3ZmE2MjdmMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vNtmB2gitCNxIhP4GkMjHcNfjeedfI4e0g8Ecguc7DE"> This feature will be implemented in the next update.

You're a saint.

**Comment by lihaoyun6** [comment]
@dhruvkb @Write 
AirBattery v1.3.4 has been released, including multiple bug fixes and new features. Please check for updates😊
