### ISSUE TITLE
logi mouse master3 not show On the list

### ISSUE THREAD

**Issue by lizhelang** [lihaoyun6/AirBattery#28]

**Comment by lihaoyun6** [comment]
AirBattery obtains battery usage by reading the "broadcast data" of BLE devices. But once some Bluetooth peripherals are connected to the host (your Mac), they will stop sending public broadcasts, which helps save power.

So when your mouse is connected to your Mac, AirBattery cannot obtain its battery data. (Batteries/AirBuddy also has the same problem)

**Comment by bpetrynski** [comment]
@lihaoyun6 I noticed that somehow [BetterMouse](https://better-mouse.com/) manages to retrieve this data, even after connecting 🤔

**Comment by lihaoyun6** [comment]
I added the ability to read the battery usage of third-party Bluetooth HID devices to AirBattery starting from v1.4.0
Please update to the latest version to get all new features and fixes☺️
(and if it works, please don't forget to close this issue)

**Comment by jiaoting** [comment]
1.4.7版本，罗技anywhere鼠标，电池电量无显示哦，但在系统蓝牙里面是有显示的

**Comment by lihaoyun6** [comment]
> 1.4.7版本，罗技anywhere鼠标，电池电量无显示哦，但在系统蓝牙里面是有显示的

有尝试过在airbattery运行的情况下重新开关一下鼠标电源吗

**Comment by jiaoting** [comment]
> > 1.4.7版本，罗技anywhere鼠标，电池电量无显示哦，但在系统蓝牙里面是有显示的
> 
> 有尝试过在airbattery运行的情况下重新开关一下鼠标电源吗

试过了，没有用

**Comment by jiaoting** [comment]
罗技mx anywhere 3也不行
<img width="825" alt="image" src="https://github.com/user-attachments/assets/a2c4c13e-2157-4326-9da5-67e4df201247">

**Comment by jinghuijiang1993** [comment]
my mouse is MX anywhere 2s.I have the same problem as well.I can know my battery of my mouse by widget of system,but airbatter can't obtain the battery of my mouse.
