### ISSUE TITLE
Battery info from other macOS/Macbook devices?

### ISSUE THREAD

**Issue by varoudis** [lihaoyun6/AirBattery#29]
when you are on your stationary mac (imac,mini etc) it would be nice to see your macbook charge. is that possible?

**Comment by lihaoyun6** [comment]
I should be able to do this, but I can't do "zero configuration".  
You will get the status of your other Macs that are nearby as well as their peripherals, but you have to install AirBattery on all your Macs, just like Cloud Battery.  
Is this tolerable?🤔

**Comment by lihaoyun6** [comment]
If this is acceptable, I'll add it to my todo list.

**Comment by varoudis** [comment]
> I should be able to do this, but I can't do it "zero configuration" You will get the status of your other Macs that are nearby as well as their peripherals, but you have to install AirBattery on all your Macs, just like Cloud Battery. Is this tolerable?🤔

Sound ok! no prob.

How is the power saving on mobile devices in relation to your app? I think the probing timing can be even slower/longer.

If all macOS devices run your app, pulling will probably be a lot of "wake-up" from deeper power states. no?

**Comment by lihaoyun6** [comment]
Pulling data from an iOS device does not significantly affect its battery life.
Because before communicating with the device, AirBattery will detect whether it is "online" (the sleeping iPhone/iPad will wake up periodically to receive messages, update weather, upload backup, etc.)
So AirBattery will only communicate with these devices when they are already in a "half-awake" state, instead of forcing them to wake up.

**Comment by varoudis** [comment]
What is the "long" pulling rate? Can you add an option for "custom minutes".
Thanks!

**Comment by lihaoyun6** [comment]
And for BLE peripherals, reading their battery data will not reduce battery life  
Because whether you read them or not, they are sending public broadcasts on their own. Just like when you listen to FM radio, the transmission power of the radio station has nothing to do with the number of listeners

**Comment by lihaoyun6** [comment]
> What is the "long" pulling rate? Can you add an option for "custom minutes". Thanks!

short = 1min  
medium = 2min  
long = 3min

**Comment by lihaoyun6** [comment]
`"Can you add an option for custom minutes"`

Ok, I'll put it on my todo list

**Comment by lihaoyun6** [comment]
AirBattery v1.3.5 has been released. In the new version, you can set any update interval (between 1 ~ 99 minutes)

**Comment by lihaoyun6** [comment]
> when you are on your stationary mac (imac,mini etc) it would be nice to see your macbook charge. is that possible?

AirBattery v1.3.6 has been released!  
You can use the new "Nearcast" feature to check the battery status of other Macs and their peripherals in the same LAN at any time.
