### ISSUE TITLE
Reload widget

### ISSUE THREAD

**Issue by Alrazzouq** [lihaoyun6/AirBattery#31]
I have a suggestion: double click on a widget → reload (update) it.

**Comment by lihaoyun6** [comment]
Apple does not allow widgets to respond to such complex actions. Apple believes that widgets are only for viewing.
If you need to reload widgets, please open Settings > "Widget" and click "Reload All Widgets"

**Comment by infinitepower18** [comment]
With macOS Sonoma's interactive widgets, could there be a refresh button on the widget itself?

**Comment by lihaoyun6** [comment]
> With macOS Sonoma's interactive widgets, could there be a refresh button on the widget itself?

🤔It should work, I'll give it a try

**Comment by Alrazzouq** [comment]
Actually in Version 1.3.1  of the application, there was an action on clicking on the widget which opened the application.

**Comment by lihaoyun6** [comment]
@Alrazzouq  @infinitepower18  
I did it with URL Schame. In the next version, when you click on any widget, AirBattery will refresh all of them!

**Comment by lihaoyun6** [comment]
This issue has been fixed in AirBattery v1.3.5, please update to the latest version
