### ISSUE TITLE
Panel cuts off screen

### ISSUE THREAD

**Issue by infinitepower18** [lihaoyun6/AirBattery#32]
If the dock icon is near the end of the screen, the panel will cut off the screen.

<img width="230" alt="Screenshot 2024-06-07 at 5 32 50 PM" src="https://github.com/lihaoyun6/AirBattery/assets/44692189/25a4af61-4d3e-4fc8-b79f-f633a08d94a0">

**Comment by lihaoyun6** [comment]
ok, it will be fixed in the next version

**Comment by lihaoyun6** [comment]
This issue has been fixed in AirBattery v1.3.5, please update to the latest version
