### ISSUE TITLE
Matching AirPods icon to correct gen

### ISSUE THREAD

**Issue by Ender-Wang** [lihaoyun6/AirBattery#35]
I noticed that the AirPods icon in the widget indicates the first-gen design, while mine is gen 2, can you differentiate those in the future? Btw, I saw MacBook icon matches my 14", which is great :D

**Comment by Alrazzouq** [comment]
If there is an option to customise the icon, it will be great.

**Comment by lihaoyun6** [comment]
There is no difference in appearance between the first and second generation of AirPods. In Apple's SFSymbol, these two models also share the same icon.
<img width="706" alt="image" src="https://github.com/lihaoyun6/AirBattery/assets/16348097/72948d72-28b3-43d3-8353-b4c40a2f2072">
![image](https://github.com/lihaoyun6/AirBattery/assets/16348097/70a2e90f-83ce-48d9-b053-3c73570189e1)

**Comment by Ender-Wang** [comment]
> There is no difference in appearance between the first and second generation of AirPods. In Apple's SFSymbol, these two models also share the same icon.
> <img width="706" alt="image" src="https://github.com/lihaoyun6/AirBattery/assets/16348097/72948d72-28b3-43d3-8353-b4c40a2f2072">
> ![image](https://github.com/lihaoyun6/AirBattery/assets/16348097/70a2e90f-83ce-48d9-b053-3c73570189e1)
> 
> 

Sorry for the misleading, but I mean the case, gen 2 case has two versions imk, the default one has no LED charging light hole on the outside of the case, then Apple saled another case that support wireless charging with a charging light on the outside of the case, and Apple quietly discontinued it. Now you cannot even find on Apple's website lmao. My airpods 2 case is the default one without the charging light on the outside of the case.

**Comment by lihaoyun6** [comment]
Sorry, Apple doesn’t reflect this difference in the device ID. So AirBattery can only identify your device as AirPods 2, but not what version of its case it is (Maybe the built-in widget in macOS that can detect this, but I don't know how it does it)😥

**Comment by Ender-Wang** [comment]
Actually Apple uses the one with the charging light even it should be the one without it lmao, Apple does not pay much attention to details in those days ngl.

**Comment by Ender-Wang** [comment]
![CleanShot_2024-06-10_18-23-41](https://github.com/lihaoyun6/AirBattery/assets/33310255/f8623f64-512e-417c-867a-c1fb6c278083)

Not sure what's going on, but my AirPods is the second-gen, definitely not AirPods pro. 
AirBattery: 1.3.5
macOS 14.5, 14 inch.

**Comment by lihaoyun6** [comment]
> 
> Not sure what's going on, but my AirPods is the second-gen, definitely not AirPods pro. AirBattery: 1.3.5 macOS 14.5, 14 inch.

Due to a branch switching error, the correct icon was not found and the default AirPods Pro icon was returned. This problem will be fixed in the next update

**Comment by lihaoyun6** [comment]
> 
> Not sure what's going on, but my AirPods is the second-gen, definitely not AirPods pro. AirBattery: 1.3.5 macOS 14.5, 14 inch.

This issue has been fixed in AirBattery v1.3.6
