### ISSUE TITLE
Beats Studio Pro headphones displayed as earbuds

### ISSUE THREAD

**Issue by fuzzywankenobi** [lihaoyun6/AirBattery#36]
Oddly, my Beats Studio Pro headphones show up as three separate devices, with identifiers and icons that belong to the Beats Studio Buds:

<img width="391" alt="AirBattery Window" src="https://github.com/lihaoyun6/AirBattery/assets/112252645/acd20bbc-0194-45cf-a98b-c4d5f6c83e2b">

Only the so-called right earbud shows the actual battery level — the others seem to be permanently set at 15%. Is AirBattery just mistaking them for earbuds and showing a placeholder level for the non-existent case and left bud, or does macOS actually see them as three devices? 🤔

It's also curious that they're displayed as "LE-_username_'s Beats Studio Pro" instead of the custom names I created for them. The other devices show my custom names.

<img width="335" alt="Control Center" src="https://github.com/lihaoyun6/AirBattery/assets/112252645/de99543a-31c8-411c-afd1-20fb322e33b1">

Here are the details from System Information > Bluetooth:

> Beats Studio Pro:
>   Vendor ID:	0x004C
>   Product ID:	0x2017
>   Firmware Version:	2B68
>   Minor Type:	Headphones

**Comment by lihaoyun6** [comment]
I think it's because I confused `Studio Pro` and `Studio Buds` (I don't have these headphones to test), this will be fixed in the next update
But the problem with the device name I can't solve for now, the custom name seems to be stored in macOS instead of the device flash memory 🤔

**Comment by lihaoyun6** [comment]
This issue has been fixed in AirBattery v1.3.6

**Comment by fuzzywankenobi** [comment]
Working as expected now.
