### ISSUE TITLE
iPhone and Watch battery not showing up

### ISSUE THREAD

**Issue by AnshumGill** [lihaoyun6/AirBattery#38]
I've updated to 1.3.6 and am only able to see airpods battery in the widgets. iPhone did show up momentarily but restarting the app made that disappear as well and it hasn't been added back.

Could you guide me how I can help you troubleshoot this? Are there any logs I can look at to see what may be going wrong in the discovery part? 

Also for bluetooth devices like Logitech Mouse and a mechanical keyboard, I read that once they are connected they stop broadcasting and that is you are not able to discover them, however they do show up on the default battery widget, are you aware on how the default widget could be collecting this?

Thanks!

**Comment by AnshumGill** [comment]
These are my settings btw
![image](https://github.com/lihaoyun6/AirBattery/assets/36377026/5d4aa4a4-20e8-484d-bf1b-db5d779cadc8)

iPhone and Watch used to show up fine on 1.3.3, but since updating they are missing, I've tried downgrading to 1.3.3/4/5 but no luck

**Comment by lihaoyun6** [comment]
Actually v1.3.6 did not change the device discovery code. Please try restart your Mac.

As for the built-in widgets of macOS, because macOS is already connected to these devices, it can directly ask the devices to provide their device information, rather than just passively receiving broadcasts. In this case, the data is transmitted between the peripheral and the host through regular BT channels. AirBattery cannot spy on this data

**Comment by AnshumGill** [comment]
I've tried a couple of restarts still experiencing the same. Is there any way I can help troubleshoot? 

Understood your point on other BT devices.

**Comment by lihaoyun6** [comment]
I can't reproduce this 😢
You could try connecting your iPhone to your Mac via USB and wait a few minutes to see if it shows up in the list, then disconnect

**Comment by AnshumGill** [comment]
Okay connecting via cable made the watch and iPhone show up immediately. Removing the cable their information is not getting updated, guessing it's not able to reach them somehow. I'll try restarting all my devices.

**Comment by lihaoyun6** [comment]
Don't forget to check your iPhone's WiFi connection. Depending on your settings, your iPhone will only be discoverable if it is on the same LAN as your Mac.

**Comment by AnshumGill** [comment]
Okay restarting all devices seems to have done the trick, now they are showing up.

Thanks for the help!
