### ISSUE TITLE
CPU/Battery consumption

### ISSUE THREAD

**Issue by powext** [lihaoyun6/AirBattery#39]
Hi there, 

I noticed that the app is constantly running and impacting the battery usage with a 58 score over 12 hours
![CleanShot 2024-06-12 at 13 04 10](https://github.com/lihaoyun6/AirBattery/assets/20648640/fd3c4156-f677-4dfd-a87e-6e82df245bb8)
which is not that bad but I think could be improved, specially comparing it with other major applications.

Considering that i don't care about the very precise live battery level I think it would be great if users can somehow get the data just right after opening the app or read the most recent read (every x minutes). Or maybe is the constant scanning? I don't know the codebase.
Of course this can be eventually an option in the settings.
Maybe this is just a bug and I'm overhinking

**Comment by lihaoyun6** [comment]
<img width="666" alt="image" src="https://github.com/lihaoyun6/AirBattery/assets/16348097/d0cc4fdc-2a91-45ca-a485-ccb6f21d0570">

Thanks for reminding me of this!!!  
I was so busy adding new features to AirBattery that I forgot to optimize its power consumption.
5.3... OMG, this is crazy, something is wrong. It should be between 0.1 ~ 0.7

**Comment by lihaoyun6** [comment]
OK, I caught it. An incorrect TimeInterval made a Timer go crazy. I will fix this in the next version
