### ISSUE TITLE
Vision Pro有办法支持吗？

### ISSUE THREAD

**Issue by nasyxx** [lihaoyun6/AirBattery#4]
如题.

**Comment by nasyxx** [comment]
我的错（奇怪，戴着的时候，没有摘下来，反倒出现了

**Comment by nasyxx** [comment]
现在没有图标

<img width="368" alt="Screenshot 2024-04-09 at 4 37 58 AM" src="https://github.com/lihaoyun6/AirBattery/assets/5007613/48283e59-6765-4997-99f5-14e8487ed240">

**Comment by lihaoyun6** [comment]
请在确保 AirBattery 菜单中正在显示你的 Vision Pro 的情况下, 打开`访达`并点击菜单栏上的`前往`>`前往文件夹...`  
然后将下面一行复制粘贴到地址栏里, 并确认:
```
~/Library/Containers/com.lihaoyun6.AirBattery.widget/Data/tmp
```
进入这个文件夹之后, 将其中的`temp.json`右键用文本编辑器打开, 并搜索`deviceType`
会出现很多个搜索结果, 找到你 Vision Pro 名字后面最近的一条, 记录下他的值 (例如"deviceType":"Trackpad")
然后再搜索`deviceModel`, 同样找到  Vision Pro 名字后面最近的一条, 并记录下他的值(例如"deviceModel":"AbcdeFg")
将这两个值回复给我, 因为我手中没有 Vision Pro 的真机, 我需要这些设备信息才能用于识别此机型

请放心, 这两个值只是通用的设备型号代码, 在所有同款设备上都是一样的, 不包含任何个人隐私信息, 可以放心公开

**Comment by nasyxx** [comment]
```json
{
    "acPowered": false,
    "lastUpdate": 1712670784.54286,
    "deviceID": "",
    "isHidden": false,
    "deviceName": "Nasy’s Apple Vision Pro",
    "isCharging": 0,
    "deviceType": "RealityDevice",
    "hasBattery": true,
    "isPaused": false,
    "parentName": "",
    "deviceModel": "RealityDevice14,1",
    "isCharged": false,
    "batteryLevel": 100
  },
```

是这个吗？

**Comment by lihaoyun6** [comment]
https://github.com/lihaoyun6/AirBattery/releases/tag/1.2.8
你试一下这个pre-release, 我在里面修复了 AirPods Max 显示为多个设备的 bug, 还添加了对 Vision Pro 的识别和图标
如果可以正常工作烦请回复一下, 我会把它标记为正式release

**Comment by nasyxx** [comment]
<img width="198" alt="Screenshot 2024-04-09 at 11 00 12 PM" src="https://github.com/lihaoyun6/AirBattery/assets/5007613/71719b12-64cc-4055-bb11-671db540144d">

嗯，应该是没什么问题了
