### ISSUE TITLE
Custom charge/discharge threshold notification and notification settings per device.

### ISSUE THREAD

**Issue by sohate** [lihaoyun6/AirBattery#47]
Hello! Thanks for great app! Can you please add custom charge/discharge threshold notification and notification settings per device. Thanks!

**Comment by lihaoyun6** [comment]
I completely refactored the battery alert feature in v1.5.8, and now you can add different alert configurations for any device.
Configurable items include: whether to enable `full battery alert` or `low battery alert`, as well as the specific threshold and whether to make a sound.

**Comment by lihaoyun6** [comment]
> @lihaoyun6 Just updated to 1.5.8 and alert sections is completely lost. macOS Sonoma 14.7 

Yes, this is normal. Starting from v1.5.8, the battery alert configuration will be independent for each device.  
You can create/delete or modify the battery alert configuration for any device by clicking on the "bell" button for each device in the device list.
<img width="339" alt="image" src="https://github.com/user-attachments/assets/36775472-3c50-4135-a45f-034575141d4e">
