### ISSUE TITLE
macOS 15 编辑小组件里面没 AirBattery

### ISSUE THREAD

**Issue by i0czf** [lihaoyun6/AirBattery#48]

**Comment by soapffz** [comment]
同样问题，macOS 14也是，编辑小组件里面没有AirBattery，重启无法解决，任务栏正常桌面小组件中没有

**Comment by lihaoyun6** [comment]
建议检查一下磁盘, 不要让多个AirBattery.app副本同时存在, 这会导致系统的小组件引擎无法确定该从哪个版本的app加载插件

**Comment by tttttb** [comment]
我卸载后，从brew重新安装的，问题依然存在

**Comment by lihaoyun6** [comment]
我使用macOS 15 beta1和beta2都没有复现这个情况. 很大概率是系统本身不稳定导致的.
目前macOS 15依旧处于功能快速迭代的时期, 除了导致无法运行的严重问题, 我暂时不打对进行针对性修复.
等正式版发布前夕再说吧

**Comment by tttttb** [comment]
今天更新app，问题解决了
