### ISSUE TITLE
使用蓝牙发现的话会造成airpods音乐卡顿

### ISSUE THREAD

**Issue by bboysoulcn** [lihaoyun6/AirBattery#5]

**Comment by bboysoulcn** [comment]
m1 mac mini

**Comment by lihaoyun6** [comment]
测试了一会, 暂时没有成功复现.  
不过 Apple Silicon 的蓝牙协议栈确实一直比较羸弱, 稍微大一点的数据量或者干扰, 甚至只是更频繁的监听广播数据都有一定的可能性会导致蓝牙传输出现卡顿.
感觉你遇到的本质还是信号强度问题, 可能是机箱摆放位置/距离导致信号不够强, 所以在 AirBattery 突发搜索的情况下倒是数据传输卡顿

**Comment by bboysoulcn** [comment]
> 测试了一会, 暂时没有成功复现. 不过 Apple Silicon 的蓝牙协议栈确实一直比较羸弱, 稍微大一点的数据量或者干扰, 甚至只是更频繁的监听广播数据都有一定的可能性会导致蓝牙传输出现卡顿. 感觉你遇到的本质还是信号强度问题, 可能是机箱摆放位置/距离导致信号不够强, 所以在 AirBattery 突发搜索的情况下倒是数据传输卡顿

tks bro
