### ISSUE TITLE
Neighboring incremental upgrade only? Can we skip it?

### ISSUE THREAD

**Issue by Ender-Wang** [lihaoyun6/AirBattery#58]
- I just noticed that I have not upgraded AirBattery for a few minor versions, I noticed that I indeed ticked auto-upgrade and auto-download. 
- When I manually checked for updates, I only got the next miner upgrade, not the latest one, so I needed to install that update and check again to install the newer version. Which seems annoying especially since the auto-update does not seem to work.
- Can you maybe check for the latest version, do a full install, and skin those miner versions in between?

**Comment by lihaoyun6** [comment]
Sorry, I can't reproduce this issue.  
I tried installing AirBattery v1.4.0 and even v1.3.5 and checking for updates, and it can be directly upgraded to v1.4.4. Maybe you are experiencing some weird network cache issues? 🤔

**Comment by Ender-Wang** [comment]
Thanks, that's weird tho. I will keep an eye on the coming updates.
