### ISSUE TITLE
m1 mba 图标显示错误&设备名未读取

### ISSUE THREAD

**Issue by nidongpinyinme** [lihaoyun6/AirBattery#6]
m1的mba是没有刘海的，图标显示了刘海，当然这是小问题。但是其他设备都读取了设备名，但是当前使用的设备似乎没有读取设备名。

**Comment by lihaoyun6** [comment]
关于设备名的问题就是这么设计的：针对“此Mac”显示的并不是设备名，而是设备型号
关于设备图标是因为苹果近些年更换了mac的型号识别符格式，导致很难通过正则的方式来匹配具体的机型，我又懒得拉一长串设备列表做一一查询，所以就给所有MacBook Pro统一用了刘海的图标😂

**Comment by lihaoyun6** [comment]
这个图标问题目前暂时不影响使用，但既然你提出了这个问题，后续我可能会精细适配一下吧。这个issue就先留着

**Comment by lihaoyun6** [comment]
<img width="352" alt="image" src="https://github.com/lihaoyun6/AirBattery/assets/16348097/99adb8b6-be3e-4134-9f7c-23956462f4a6">

你的这两个需求已经实现好了, 更新 [v1.2.9](https://github.com/lihaoyun6/AirBattery/releases/tag/1.2.9) 版本就可以了
这个版本将本机Mac的标题从设备类型改为了设备名称, 并且对非刘海屏机型添加了识别和正确的图标
