### ISSUE TITLE
电量显示问题

### ISSUE THREAD

**Issue by Kuzmania33** [lihaoyun6/AirBattery#63]
想请教一下，蓝牙键盘为何不显示电量？需要怎么操作？非苹果蓝牙键盘

**Comment by lihaoyun6** [comment]
暂时只能做到同步读取系统显示的电量数据, 简而言之就是"macOS的蓝牙菜单里能读取到电量的设备, AirBattery就可以同步过来"  
如果系统本身就读取不到的话, 那AirBattery也无能为力
