### ISSUE TITLE
Same Headphones displayed twice

### ISSUE THREAD

**Issue by ilMagnifico** [lihaoyun6/AirBattery#66]
<img width="351" alt="Screenshot 2024-08-05 alle 17 04 53" src="https://github.com/user-attachments/assets/7516b8ae-30d1-4bd9-95bc-2d5922fbef5b">

version: 1.4.8

**Comment by lihaoyun6** [comment]
Could you please tell me the model of your headphones?
And attach a screenshot of the "Device List", like this:  
<img width="199" alt="image" src="https://github.com/user-attachments/assets/cc909cb0-dcaf-4ad0-bd92-3c1e4d0abfa0">

**Comment by ilMagnifico** [comment]
Here it is:
<img width="372" alt="Screenshot 2024-08-06 alle 10 55 53" src="https://github.com/user-attachments/assets/173e8076-9257-4c56-a8fe-643484f40f21">

But I also applied this rule:
<img width="531" alt="Screenshot 2024-08-06 alle 10 55 57" src="https://github.com/user-attachments/assets/2baf95b8-65e0-4cbd-80ca-3db931ce40e9">

**Comment by lihaoyun6** [comment]
AirBattery found your headphones from the system information and also found them through the low-power Bluetooth broadcast.   
You can exclude one of them by adding it to the blacklist, but as AirBattery tells you: "The following ***BLE*** devices will be ignored".  
So the device name you need to add to the blacklist is "LE-Bose Headphones" instead of "Bose Headphones"😊  

If all goes well, after you do this and restart AirBattery, the extra headphone will disappear.

**Comment by ilMagnifico** [comment]
> AirBattery found your headphones from the system information and also found them through the low-power Bluetooth broadcast. You can exclude one of them by adding it to the blacklist, but as AirBattery tells you: "The following _**BLE**_ devices will be ignored". So the device name you need to add to the blacklist is "LE-Bose Headphones" instead of "Bose Headphones"😊
> 
> If all goes well, after you do this and restart AirBattery, the extra headphone will disappear.

Done. Now I can't see my headphone on the widget anymore.

**Comment by lihaoyun6** [comment]
Please open the "System Information" app in Launchpad and click the "Bluetooth" on the left. Then copy all the information on the right side and send it to me.  
This can help me understand what's going on on your computer.

**Comment by ilMagnifico** [comment]
> Please open the "System Information" app in Launchpad and click the "Bluetooth" on the left. Then copy all the information on the right side and send it to me. This can help me understand what's going on on your computer.

![Uploading Screenshot 2024-08-06 alle 13.13.25.jpg…]()

**Comment by lihaoyun6** [comment]
Ok, I'll check the AirBattery code later and try to fix this (a possible solution would be to expand the blacklist so that you can block any device, not just BLE devices. That way you could keep "LE-Bose Headphones")

If there are any updates, I will come back.

**Comment by ilMagnifico** [comment]
> Ok, I'll check the AirBattery code later and try to fix this (a possible solution would be to expand the blacklist so that you can block any device, not just BLE devices. That way you could keep "LE-Bose Headphones")
> 
> If there are any updates, I will come back.

Perhaps the blacklist could be transformed into a list where you can simply check items to make them visible. This would improve the UI and offer a straightforward way to customize it. Additionally, it could be expanded in the future, allowing for ordering and further customization as needed.​

Thanks for your attention to this issue.

**Comment by lihaoyun6** [comment]
<img width="379" alt="image" src="https://github.com/user-attachments/assets/4250e253-74d3-4ade-8ce9-2398de02626a">

Would you be willing to show me these two values? I use them to identify the model of your device, and if possible maybe I can create an icon for it (like AirPods)

**Comment by Ender-Wang** [comment]
It's not showing my WH-1000XM4 via Bluetooth either: 
 ```
Vendor ID:	0x054C
Product ID:	0x0D58
```

**Comment by lihaoyun6** [comment]
@ilMagnifico In v1.4.9, I extended the blacklist to all devices. So you can try to keep BLE devices and block the "Bose Headphones"
