### ISSUE TITLE
Separate AirPods show wrong icon

### ISSUE THREAD

**Issue by ismslv** [lihaoyun6/AirBattery#69]
AirBattery 1.4.8, Sonoma 14.6

One of AirPods is out of the case, name clearly indicates that this is an AirPod Pro, but icon is of simple AirPod. The one with a wrong icon is in the ear, other is in the case.

<img width="351" alt="Screenshot 2024-08-08 at 02 51 32" src="https://github.com/user-attachments/assets/4b7a73b5-dc0a-4518-94db-708c1f151f27">

**Comment by lihaoyun6** [comment]
[AirBattery.zip](https://github.com/user-attachments/files/16538616/AirBattery.zip)

Please try this version and let me know if the issue is resolved.

**Comment by ismslv** [comment]
Thank you. Yes, looks like it fixes it, but it was a rare issue, maybe it just did not happen again.
