### ISSUE TITLE
修改设备名称后，会重复显示

### ISSUE THREAD

**Issue by LiXin-x** [lihaoyun6/AirBattery#7]
如图，修改了 AirPods Pro 的名称，会同时显示
<img width="351" alt="image" src="https://github.com/lihaoyun6/AirBattery/assets/27121050/8a39485f-290d-4f8b-8c04-6d289f25fdc1">

感谢，已经替换掉原来没啥用的电源按钮！❤️

**Comment by lihaoyun6** [comment]
Airbattery是使用设备名称来区分设备的，但并不能“某一时刻没有检测到设备，就立即将其从设备列表中删除”，因为有些时候设备还在附近，只是刚好错开了，没扫描到  
如果使用立即删除的策略，就会导致设备列表在不停的跳动，很影响使用。所以airbattery的默认策略是：即使一个设备短时间离线，也不会把它删除，直到触发了离线阈值（默认是20分钟，在设置面板里可以调节）  

综上所述，你的这种情况并不用担心，因为20分钟之后老airpods的条目就会从列表中消失
