### ISSUE TITLE
升级到1.49后，小组件怎么没有了。。

### ISSUE THREAD

**Issue by shuifa** [lihaoyun6/AirBattery#71]
升级到1.49，mac小组件找不到airbattery 的电池组件了

**Comment by lihaoyun6** [comment]
是macOS 15系统吗?

**Comment by lihaoyun6** [comment]
macOS 15系统的WidgetKit挺不稳定的, 经常无缘无故的消失又莫名其妙的自动出现. 属于系统级别的bug. 等正式版吧
或者你多重启几遍应该能好

**Comment by shuifa** [comment]
> 是macOS 15系统吗?

不是，系统是14.6.1

**Comment by shuifa** [comment]
> macOS 15系统的WidgetKit挺不稳定的, 经常无缘无故的消失又莫名其妙的自动出现. 属于系统级别的bug. 等正式版吧 或者你多重启几遍应该能好

昨天晚上使用brew 更新后之前设置的小组件直接消失了。。也找不到了。

**Comment by lihaoyun6** [comment]
<img width="354" alt="image" src="https://github.com/user-attachments/assets/af1a4572-c530-42ca-894d-ba1fdb75b02f">

我这边是一切正常的

**Comment by shuifa** [comment]
> <img alt="image" width="354" src="https://private-user-images.githubusercontent.com/16348097/356789169-af1a4572-c530-42ca-894d-ba1fdb75b02f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyNjU1NDcsIm5iZiI6MTcyMzI2NTI0NywicGF0aCI6Ii8xNjM0ODA5Ny8zNTY3ODkxNjktYWYxYTQ1NzItYzUzMC00MmNhLTg5NGQtYmExZmRiNzViMDJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEwVDA0NDcyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3YmUzYTQzMzUzMzJiMzFiYzFjNmJmZGU4ZTI2ZTExN2UwMjVmODFlMTRlMzNhODdmNmQ4YjNlY2Q2MmQyODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Wkar_J3V_ngnkfAXO0B2Mh1iR21T0dYmjtsDYT_7_DI">
> 我这边是一切正常的

<img width="460" alt="image" src="https://github.com/user-attachments/assets/0bfdd9ea-66db-41a3-b573-7f485c2bb7b7">
我这不行啊，一样的版本

**Comment by lihaoyun6** [comment]
<img width="734" alt="image" src="https://github.com/user-attachments/assets/b94ae0c9-5836-4658-8959-bc76cb9c8092">

你试试这样搜索一下, 看看是不是电脑里存在多个AirBattery的副本. 如果同时存在多个副本, 可能导致小组件框架不知道该加载哪个小组件.

**Comment by lihaoyun6** [comment]
如果确定没有其他的副本影响, 那你就重启试试吧

**Comment by shuifa** [comment]
还有就是我用的其他蓝牙键盘 
<img width="478" alt="image" src="https://github.com/user-attachments/assets/a49aa5f9-58fe-421f-bd8b-76be7c743673">
链接后也不现实键盘电量。只支持苹果的键盘吗

**Comment by lihaoyun6** [comment]
读取键鼠和读取耳机还真不一样, AirBattery只支持苹果键盘或可以在macOS的蓝牙菜单中看到电量的设备. 如果系统读不到你键盘的电量, AirBattery也很难办到

**Comment by shuifa** [comment]
> <img alt="image" width="734" src="https://private-user-images.githubusercontent.com/16348097/356789250-b94ae0c9-5836-4658-8959-bc76cb9c8092.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyNjU3MTksIm5iZiI6MTcyMzI2NTQxOSwicGF0aCI6Ii8xNjM0ODA5Ny8zNTY3ODkyNTAtYjk0YWUwYzktNTgzNi00NjU4LTg5NTktYmM3NmNiOWM4MDkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEwVDA0NTAxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0MjY4OTQ2NDdmZDg5ZDdhOTAzMWRiNWZjZTM2NDVjMTJhNzBlYmRkMDY4NTVkYjhlNzE4NjM1NGQwNTJmYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W45oZ8NGvcgwyu_IgwDJrCYRM0N9JZrcvd3k0HSjwJ4">
> 你试试这样搜索一下, 看看是不是电脑里存在多个AirBattery的副本. 如果同时存在多个副本, 可能导致小组件框架不知道该加载哪个小组件.

<img width="738" alt="image" src="https://github.com/user-attachments/assets/e66539f5-00b9-4e63-970c-72b6500d3f40">
就一个。。我一直用的brew下载更新的

**Comment by shuifa** [comment]
那只能等之后的版本看看了😭

**Comment by Tobylei** [comment]
我也遇到过相同问题，从brew下载，更新后小组件自己消失了，感觉有可能是macOS的问题

**Comment by shuifa** [comment]
多重启几次又有了😂😂愿你出走半生，归来仍是少年在 2024年8月10日，23:21，Tobylei ***@***.***> 写道：﻿
我也遇到过相同问题，从brew下载，更新后小组件自己消失了，感觉有可能是macOS的问题

**Comment by MovedInDream** [comment]
<img width="48" alt="image" src="https://github.com/user-attachments/assets/c7f1256f-260c-4f1f-b296-c3cb9fa0a220">
请问下三角形感叹号是什么意思
