### ISSUE TITLE
背景色要是能和系统自带的保持一致就好了

### ISSUE THREAD

**Issue by JuniorPan** [lihaoyun6/AirBattery#72]
背景色要是能和系统自带的保持一致就好了

**Comment by lihaoyun6** [comment]
说的是小组件吗? 这个确实做不到. 因为macOS上只有苹果的小组件才能调用高斯模糊背景, 其他第三方小组件全都无法使用. 因为苹果将其划分为私有API... 听起来很离谱, 但苹果确实就是禁止第三方小组件使用高斯模糊特效背景. 可能就是为了凸显自家第一方小组件的精致度吧😂

**Comment by JuniorPan** [comment]
确实很离谱 ~
