### ISSUE TITLE
Sony WH-1000XM4 is not showing up in widget

### ISSUE THREAD

**Issue by Ender-Wang** [lihaoyun6/AirBattery#74]
Not sure why it doesnot, seems not recognized? Some identifiers you might need:
```
Vendor ID:	0x054C
Product ID:	0x0D58
```

Left widget is AirBattery, on the right is the stock one.
![CleanShot_2024-08-13_23-59-30](https://github.com/user-attachments/assets/793adc76-0289-4213-bf5e-af960b3c6f45)

On larger stock widget:
![CleanShot_2024-08-14_00-00-14](https://github.com/user-attachments/assets/99bd770a-2b43-4ef7-ade8-fbb9dcde4ec5)

**Comment by lihaoyun6** [comment]
Please connect your headset to Mac, then open "Terminal" and run:
```bash
system_profiler SPBluetoothDataType -json > ~/Desktop/bluetooth.json
```
Then send me the `bluetooth.json` on your desktop

**Comment by Ender-Wang** [comment]
[bluetooth.json](https://github.com/user-attachments/files/16609469/bluetooth.json)
I masked the second half of the MAC address with FFF.

**Comment by lihaoyun6** [comment]
It seems that macOS does not list the battery info of the headphones here.
Have you tried enabling "Enhanced HID Scanner" and reconnecting the headphones? This will give AirBattery a chance to get the information it wants from the system log.

**Comment by Ender-Wang** [comment]
Turned on HID scan and it's showing, thanks a lot.

**Comment by iitjee** [comment]
Hi, Where can I find the option for "Enhanced HID Scanner"? I'm unable to get the battery info of mx master 2s or wh-100xm3

my bluetooth.json has

   "device_connected" : [
        {
          "BLE_TIZENRT_SCATTERNET_CLIENT" : {
            "device_address" : "28:6B:B4:FF:FF:FF,
            "device_rssi" : "-91",
            "device_services" : "0x400000 < BLE >"
          }
        },
        {
          "MX Master 2S" : {
            "device_address" : "D6:47:18:FF:FF:FF",
            "device_firmwareVersion" : "MPM12.01_0006",
            "device_minorType" : "Mouse",
            "device_productID" : "0xB019",
            "device_services" : "0x400000 < BLE >",
            "device_vendorID" : "0x046D"
          }
        },
        {
          "WH-1000XM3" : {
            "device_address" : "CC:98:8B:FF:FF:FF",
            "device_firmwareVersion" : "4.1.1",
            "device_minorType" : "Headset",
            "device_productID" : "0x0CD3",
            "device_services" : "0x800019 < HFP AVRCP A2DP ACL >",
            "device_vendorID" : "0x054C"
          }
        }
      ],
