### ISSUE TITLE
Single Device Widget Problem

### ISSUE THREAD

**Issue by chris-0111** [lihaoyun6/AirBattery#75]
When using single device widget, the device cannot be chosen when I pressed edit "AirBattery".

It shows
Enter Device Name---------------------              Text
Cannot be selected. The other widgets I can see iPhone battery, etc

**Comment by lihaoyun6** [comment]
After you paste the device name into the widget, please press the Enter key and then click "Done" instead of clicking it directly.
Otherwise macOS will discard your input. This is a bug from the system itself
