### ISSUE TITLE
小组件bug AND 是否可以支持只小组件显示

### ISSUE THREAD

**Issue by zhinianyuxin0o0** [lihaoyun6/AirBattery#8]
添加了小组件之后,小组件没有任何图标和电量.
<img width="366" alt="image" src="https://github.com/lihaoyun6/AirBattery/assets/73481491/44f49bce-622f-491a-b1a5-ac5c01f4d951">
并且想问问是不是可以支持只在小组件显示,这样更无感和方便(个人感觉).

**Comment by lihaoyun6** [comment]
> 添加了小组件之后,小组件没有任何图标和电量. <img alt="image" width="366" src="https://private-user-images.githubusercontent.com/73481491/322410540-44f49bce-622f-491a-b1a5-ac5c01f4d951.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3MDY5NTQsIm5iZiI6MTcxMzcwNjY1NCwicGF0aCI6Ii83MzQ4MTQ5MS8zMjI0MTA1NDAtNDRmNDliY2UtNjIyZi00OTFhLWIxYTUtYWM1YzAxZjRkOTUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDEzMzczNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyZDI1N2QwOWNkZjQ4N2Q1NjYyOWM4MTI2OTljN2IxZTI1YjcyMWEwZGY4ODZmM2Q0OWZhMGM0MGEyYmE3ZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MwQ6GfYMY8ayUXDyLd7saw5jOTnQ5ZpqhamuxQsxY0A"> 并且想问问是不是可以支持只在小组件显示,这样更无感和方便(个人感觉).

建议检查一下电脑上是不是存在多个AirBattery.app副本. 如果同时存在多个不同版本的app, 小组件就会错乱

**Comment by zhinianyuxin0o0** [comment]
第一次安装 我重装一次试试看吧
