### ISSUE TITLE
能否增加充满电不提醒的功能？

### ISSUE THREAD

**Issue by jiaoting** [lihaoyun6/AirBattery#83]
目前是充满电会提醒，但是手机充满了，放在充电器上，会一直不断的提醒充满电，建议增加个充满电不提醒的功能
目前可以取消这台手机的提醒，但是经常忘记充电，所以想手机没电了提醒，充满了不提醒，或者就提醒1次（提醒1次这个是不是比较难判断，建议增加个电量提醒阈值，比如掉到95%后再充电到100%才会再提醒）。
<img width="344" alt="image" src="https://github.com/user-attachments/assets/075868db-9171-4be9-ae54-5cf1a0431206">

**Comment by lihaoyun6** [comment]
我在v1.5.8中完全重构了电量提醒功能, 现在你可以为任意设备添加不同的提醒配置.  
现在你可以为任何一台设备配置是否启用`充满提醒`或`低电量提醒`, 以及具体的阈值和是否发出声音, 就像这样  
<img width="360" alt="image" src="https://github.com/user-attachments/assets/cc3c6bbb-262e-4fe4-897a-5072e3206a6e">

**Comment by jiaoting** [comment]
这个好呀
