### ISSUE TITLE
Widget color

### ISSUE THREAD

**Issue by Alrazzouq** [lihaoyun6/AirBattery#86]
I have noticed that the color of the MacBook buttery is orange while it is 40%. I think it should be green, and orange on 20%, and red on 10%.
![Screenshot 2024-10-03 at 9 37 10 PM](https://github.com/user-attachments/assets/ee31168b-e731-462b-94e8-bab862df706e)

**Comment by lihaoyun6** [comment]
In v1.5.1, AirBattery has the ability to detect whether the current Mac is in low power mode.  
When you put your Mac in low power mode, AirBattery will display its battery usage in yellow.

**Comment by Alrazzouq** [comment]
Thank you.👍👍👍
