### ISSUE TITLE
AirPods Max shown as a AirPod Pro - Version 1.5.2 - MacOS 15.0.1

### ISSUE THREAD

**Issue by mrxoom1274** [lihaoyun6/AirBattery#87]
my AirPods Max shown in the App and Widget as a AirPods Pro , one with 0% one with the real %

![87956](https://github.com/user-attachments/assets/3aafc0af-9fb8-489b-b3d5-9ccc971fecec)

**Comment by lihaoyun6** [comment]
Please open the built-in "System Information" utility in macOS and click "Bluetooth" on the left, then find your AirPods Max on the right sude and tell me its "Product ID"

**Comment by lihaoyun6** [comment]
I guess you are using the new "AirPods Max with USB-C" which should have Product ID `0x201F`  
I have added support for this model to AirBattery, but have not yet released an update. It will be available around today😁

**Comment by mrxoom1274** [comment]
Yes. Great. Thx Von meinem iPhone gesendethttps://bio.link/mfxj7m2yAm 11.10.2024 um 04:47 schrieb lihaoyun6 ***@***.***>:﻿
I guess you are using the new "AirPods Max with USB-C" which should have Product ID 0x201F
I have added support for this model to AirBattery, but have not yet released an update. It will be available around today😁

**Comment by lihaoyun6** [comment]
AirBattery v1.5.3 has been released
